version: '2'
volumes:
  resin-data:
services:
  device-check:
    build:
      context: ./device-check
      dockerfile: Dockerfile
    network_mode: host
    volumes:
      - 'resin-data:/data'
    restart: 'no'
    environment:
      - 'API_ENV=balena-cloud.com'
      - 'DEVICE_UUID=<troubleshooted device uuid>'
      - 'BALENA_TOKEN=<session token from balena-cloud>'
      - 'DBUS_SYSTEM_BUS_ADDRESS=unix:path=/host/run/dbus/system_bus_socket'
    privileged: true
    labels:
        io.balena.features.dbus: '1'
